spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: micro-config-test-dev

---
spring:
  profiles: default
  application:
    name: micro-config-test-default
